import { type ReactNode, type ElementType } from "react";
import { type SxProps, type Theme } from "@mui/material";
import type { ButtonProps } from "../Button/type";
export type ModalProps = {
  type?: "modal" | "modaless";
  position?: "basic" | "overflow";
  contentArea?: ReactNode;
  size?: number;
  customHeaderTitle?: ReactNode;
  customContentArea?: ReactNode;
  customBtnArea?: ReactNode;
  titleIcon?: ReactNode;
  titleFontSize?: string;
  titleColor?: string;
  hideSubmit?: boolean;
  handleSubmit?: () => void;
  handleClose?: () => void;
  submitLabel?: string;
  closeLabel?: string;
  open: boolean;
  sx?: SxProps<Theme>;
  component?: ElementType;
  title?: string;
  hideCloseBtn?: boolean;
  disabled?: boolean;
  isScreenPopup?: boolean;
  leftBtns?: ButtonProps[];
  middleBtns?: ButtonProps[];
  height?: number;
  removePadding?: boolean;
  hideHeader?: boolean;
  hideFooter?: boolean;
  overflowHidden?: boolean;
  paperClassName?: string;
  modalContentClassName?: string;
  maxWidthTitle?: string;
  titleTooltipInfo?: string;
};
